-- ============================================================
-- Entity: sch_2
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: sch_2

entity sch_2 is
  Port (
    in0 : in  STD_LOGIC;
    in1 : in  STD_LOGIC;
    out0 : out STD_LOGIC
  );
end sch_2;

architecture Behavioral of sch_2 is
  signal n1_o : STD_LOGIC;
begin

  -- combinational logic
  n1_o <= in0 or in1;

  -- output drivers
  out0 <= n1_o;

end Behavioral;

-- ============================================================
-- Entity: sch_1
-- ============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: sch_1

entity sch_1 is
  Port (
    in0 : in  STD_LOGIC;
    in1 : in  STD_LOGIC;
    out0 : out STD_LOGIC
  );
end sch_1;

architecture Behavioral of sch_1 is
  component sch_2
    Port (
      in0 : in  STD_LOGIC;
      in1 : in  STD_LOGIC;
      out0 : out STD_LOGIC
    );
  end component;
  signal n1_out0 : STD_LOGIC;
begin

  -- sub-component instantiations
  u_0_c11 : sch_2 port map (
    in0 => in0,
    in1 => in1,
    out0 => n1_out0
  );

  -- output drivers
  out0 <= n1_out0;

end Behavioral;