"""
vhdl_exemplars.py — a curated, VERIFIED VHDL reference corpus for the RAG, aimed at the
VHDL->schematic path (the editor's parseVhdl handles gate-level dataflow + a process D-FF +
when/else MUX). Two sources, both correct by construction:
  * combinational: generated by the deterministic engine (gen_vhdl over exemplars/parametric)
    -> gate-level dataflow (q <= a and b;) that the editor parses straight into a schematic.
  * sequential: hand-written standard synthesizable templates (D-FF, T-FF, JK-FF, register,
    shift register, up/down counter) — textbook-correct, good few-shot for the LLM.

build_index.py ingests these as group "vhdl_ref" (verified, schematic_ready flagged per record),
so retrieval prefers clean schematic-ready VHDL over the broad external GitHub dump.
"""
from __future__ import annotations
import re, sys
from pathlib import Path

_AI = Path(__file__).resolve().parent.parent
if str(_AI) not in sys.path:
    sys.path.insert(0, str(_AI))

import gen_vhdl               # noqa: E402
import exemplars             # noqa: E402
import parametric as P       # noqa: E402


def _san(name: str) -> str:
    s = re.sub(r"[^A-Za-z0-9_]+", "_", (name or "ckt")).strip("_").lower()
    return s or "ckt"


def _entities(code: str):
    return re.findall(r"(?:entity|architecture)\s+([A-Za-z_]\w*)", code, re.I)


# ---- combinational: correct + editor-parseable, straight from the engine ----
def _combinational():
    seen = set()
    specs = list(exemplars._build())            # (title, keywords, intent-with-equations)
    # a few extra parametric widths worth having in the library
    specs += [
        ("4-bit ripple-carry adder", ["adder", "ripple carry", "4 bit", "add", "sum", "carry"], P.nbit_adder(4)),
        ("8-bit ripple-carry adder", ["adder", "ripple carry", "8 bit", "add"], P.nbit_adder(8)),
        ("4-bit subtractor", ["subtractor", "subtract", "minus", "4 bit", "difference"], P.nbit_subtractor(4)),
        ("8-to-1 multiplexer", ["mux", "multiplexer", "8 to 1", "select"], P.nbit_mux(8)),
        ("3-to-8 decoder", ["decoder", "3 to 8", "minterm"], P.decoder(3)),
        ("4-bit comparator", ["comparator", "compare", "4 bit", "equal", "greater", "less"], P.nbit_comparator(4)),
        ("8-input priority encoder", ["priority", "encoder", "8 input"], P.priority_encoder(8)),
    ]
    for title, kw, intent in specs:
        ent = _san(title)
        if ent in seen:
            continue
        seen.add(ent)
        try:
            code = gen_vhdl.generate_vhdl(intent, ent)
        except Exception:
            continue
        yield {"title": title, "keywords": kw, "code": code, "kind": "combinational",
               "schematic_ready": True, "intent": intent}


# ---- sequential: hand-written, textbook-correct synthesizable VHDL ----
def _reg_vec(name, body_ports, body_arch):
    return (
        "library IEEE;\nuse IEEE.STD_LOGIC_1164.ALL;\n\n"
        f"entity {name} is\n  port (\n{body_ports}\n  );\nend {name};\n\n"
        f"architecture rtl of {name} is\n{body_arch}\nend rtl;\n"
    )


def _sequential():
    out = []
    out.append(("D flip-flop", ["d flip flop", "dff", "flip flop", "register", "rising edge", "clock"], True,
        "library IEEE;\nuse IEEE.STD_LOGIC_1164.ALL;\n\n"
        "entity dff is\n  port ( clk : in std_logic; d : in std_logic; q : out std_logic );\nend dff;\n\n"
        "architecture rtl of dff is\n  signal qr : std_logic := '0';\nbegin\n"
        "  process(clk)\n  begin\n    if rising_edge(clk) then\n      qr <= d;\n    end if;\n  end process;\n"
        "  q <= qr;\nend rtl;\n"))
    out.append(("D flip-flop with async reset", ["d flip flop", "dff", "reset", "async", "clear"], True,
        "library IEEE;\nuse IEEE.STD_LOGIC_1164.ALL;\n\n"
        "entity dff_rst is\n  port ( clk, rst : in std_logic; d : in std_logic; q : out std_logic );\nend dff_rst;\n\n"
        "architecture rtl of dff_rst is\n  signal qr : std_logic := '0';\nbegin\n"
        "  process(clk, rst)\n  begin\n    if rst = '1' then\n      qr <= '0';\n"
        "    elsif rising_edge(clk) then\n      qr <= d;\n    end if;\n  end process;\n  q <= qr;\nend rtl;\n"))
    out.append(("T flip-flop (toggle)", ["t flip flop", "tff", "toggle", "flip flop"], True,
        "library IEEE;\nuse IEEE.STD_LOGIC_1164.ALL;\n\n"
        "entity tff is\n  port ( clk, t : in std_logic; q : out std_logic );\nend tff;\n\n"
        "architecture rtl of tff is\n  signal qr : std_logic := '0';\nbegin\n"
        "  process(clk)\n  begin\n    if rising_edge(clk) then\n      if t = '1' then qr <= not qr; end if;\n"
        "    end if;\n  end process;\n  q <= qr;\nend rtl;\n"))
    out.append(("JK flip-flop", ["jk flip flop", "jkff", "flip flop"], True,
        "library IEEE;\nuse IEEE.STD_LOGIC_1164.ALL;\n\n"
        "entity jkff is\n  port ( clk, j, k : in std_logic; q : out std_logic );\nend jkff;\n\n"
        "architecture rtl of jkff is\n  signal qr : std_logic := '0';\nbegin\n"
        "  process(clk)\n  begin\n    if rising_edge(clk) then\n"
        "      if    j = '1' and k = '0' then qr <= '1';\n"
        "      elsif j = '0' and k = '1' then qr <= '0';\n"
        "      elsif j = '1' and k = '1' then qr <= not qr;\n"
        "      end if;\n    end if;\n  end process;\n  q <= qr;\nend rtl;\n"))
    for n in (4, 8):
        out.append((f"{n}-bit register (parallel load)", ["register", f"{n} bit", "parallel load", "store", "latch"], True, _reg_vec(
            f"reg{n}",
            f"    clk : in std_logic;\n    d   : in std_logic_vector({n-1} downto 0);\n    q   : out std_logic_vector({n-1} downto 0)",
            f"  signal r : std_logic_vector({n-1} downto 0) := (others => '0');\nbegin\n"
            "  process(clk)\n  begin\n    if rising_edge(clk) then\n      r <= d;\n    end if;\n  end process;\n  q <= r;")))
        out.append((f"{n}-bit shift register (serial in)", ["shift register", f"{n} bit", "serial in", "shift", "sipo"], True, _reg_vec(
            f"shift{n}",
            f"    clk, sin : in std_logic;\n    q : out std_logic_vector({n-1} downto 0)",
            f"  signal r : std_logic_vector({n-1} downto 0) := (others => '0');\nbegin\n"
            "  process(clk)\n  begin\n    if rising_edge(clk) then\n"
            f"      r <= r({n-2} downto 0) & sin;\n    end if;\n  end process;\n  q <= r;")))
        out.append((f"{n}-bit up counter", ["counter", "up counter", f"{n} bit", "count up", "increment"], False, _reg_vec(
            f"upcount{n}",
            f"    clk, rst : in std_logic;\n    q : out std_logic_vector({n-1} downto 0)",
            f"  signal c : unsigned({n-1} downto 0) := (others => '0');\nbegin\n"
            "  process(clk)\n  begin\n    if rising_edge(clk) then\n      if rst = '1' then c <= (others => '0');\n"
            "      else c <= c + 1; end if;\n    end if;\n  end process;\n  q <= std_logic_vector(c);",
        ).replace("use IEEE.STD_LOGIC_1164.ALL;", "use IEEE.STD_LOGIC_1164.ALL;\nuse IEEE.NUMERIC_STD.ALL;")))
        out.append((f"{n}-bit down counter", ["counter", "down counter", f"{n} bit", "count down", "decrement"], False, _reg_vec(
            f"downcount{n}",
            f"    clk, rst : in std_logic;\n    q : out std_logic_vector({n-1} downto 0)",
            f"  signal c : unsigned({n-1} downto 0) := (others => '0');\nbegin\n"
            "  process(clk)\n  begin\n    if rising_edge(clk) then\n      if rst = '1' then c <= (others => '0');\n"
            "      else c <= c - 1; end if;\n    end if;\n  end process;\n  q <= std_logic_vector(c);",
        ).replace("use IEEE.STD_LOGIC_1164.ALL;", "use IEEE.STD_LOGIC_1164.ALL;\nuse IEEE.NUMERIC_STD.ALL;")))
    for title, kw, sr, code in out:
        yield {"title": title, "keywords": kw, "code": code, "kind": "sequential",
               "schematic_ready": sr, "intent": None}


def records():
    def _s(*parts):
        acc = []
        for p in parts:
            if p is None: continue
            acc.append(" ".join(map(str, p)) if isinstance(p, (list, tuple)) else str(p))
        return "  ".join(acc)
    i = 0
    for rec in list(_combinational()) + list(_sequential()):
        ents = _entities(rec["code"])
        yield {
            "id": f"vhdlref-{i}", "group": "vhdl_ref", "source": "engine/vhdl_exemplars",
            "title": rec["title"], "topic": "vhdl|" + rec["kind"],
            "text": _s(rec["title"], rec["keywords"], "VHDL", ents, rec["code"][:1600]),
            "meta": {"verified": True, "schematic_ready": rec["schematic_ready"],
                     "kind": rec["kind"], "entities": ents, "license": "engine-generated"},
            "payload": {"code": rec["code"], "intent": rec.get("intent")},
        }
        i += 1


if __name__ == "__main__":
    n = 0
    for r in records():
        n += 1
        print(f"[{r['meta']['kind']:13}] {r['title']}  ({', '.join(r['meta']['entities'][:2])})")
    print("total vhdl_ref records:", n)
