/* ===== 22. A library of parts that PROVE themselves (build_part / list_parts) =====================
   From testing the local agent: a 4B model wrote the full adder's equations right, then typed the
   truth table wrong (sum "00001110"), built it, "verified" it against the same wrong columns and
   saved it to the module library. Small models are good at choosing and connecting parts, bad at
   producing bits. So the parts come from here: each kind is generated by code AND checked against
   a reference model (every row when the inputs allow, else ~300 vectors incl. the corners; for
   sequential parts, a clock-by-clock run against a state model) before it is handed over. A part
   that fails its own check is never drawn. The sheet is stamped verified (sheetVerifyStamp) — the
   stamp dies with the next edit (a connectivity hash), and save_module (23-…) asks for it. */

/* ---- connectivity hash of one sheet: parts + params + nets, not positions ---- */
function sheetHash(sch){
  const out=[];
  sch.components.filter(c=>c.type!=="JUNCTION").map(c=>c.id+"|"+c.type+"|"+JSON.stringify(c.params||{})).sort().forEach(x=>out.push(x));
  try{ const seen=new Set(); sch.wires.forEach(w=>{ if(seen.has(w.id)) return; const ids=[...netWires(sch,w)]; ids.forEach(i=>seen.add(i));
    const ends=new Set(); ids.forEach(i=>{ const x=sch.wires.find(q=>q.id===i); if(!x) return;
      [x.from,x.to].forEach(e=>{ const c=comp(e.cid,sch); if(c&&c.type!=="JUNCTION") ends.add(e.cid+"."+e.pid); }); });
    out.push("net:"+[...ends].sort().join(",")); }); }catch(_){}
  const str=out.join("\n"); let h=2166136261>>>0;
  for(let i=0;i<str.length;i++){ h^=str.charCodeAt(i); h=Math.imul(h,16777619)>>>0; }
  return h.toString(16)+"-"+str.length;
}
function sheetVerifyStamp(sch, how){ sch.verified={how, hash:sheetHash(sch), at:Date.now()}; }
function sheetVerified(sch){ return !!(sch && sch.verified && sch.verified.hash===sheetHash(sch)); }

/* ---- small intent builders ---- */
function ptIntent(module){
  const C=[], N=[]; let g=0;
  const it={module, components:C, nets:N,
    IN:(name)=>{ C.push({id:"i_"+name, type:"IN", name}); return "i_"+name; },
    OUT:(name, from)=>{ C.push({id:"o_"+name, type:"OUT", name}); N.push({from, to:"o_"+name}); },
    G:(type, ins)=>{ const id=type.toLowerCase()+(g++); C.push({id, type}); ins.forEach(s=>N.push({from:s, to:id})); return id; },
    X:(type, extra)=>{ const id=type.toLowerCase()+(g++); C.push(Object.assign({id, type}, extra||{})); return id; },
    W:(from, to)=>N.push({from, to}) };
  return it;
}
const ptBits=(v,i)=>(v>>>i)&1;
/* a combinational part as a truth table over per-bit input names (first = MSB of the row) */
function ptFromTable(module, inNames, outNames, fn){
  const rows={}; outNames.forEach(o=>rows[o]=[]);
  const n=inNames.length;
  for(let r=0;r<(1<<n);r++){ const v={}; inNames.forEach((nm,i)=>v[nm]=(r>>(n-1-i))&1);
    const o=fn(v); outNames.forEach(nm=>rows[nm].push(o[nm]==null?"x":String(o[nm]?1:0))); }
  const t=ttToIntent(inNames, outNames, rows, module);
  if(t.error) throw new Error(t.error);
  return t.intent;
}
/* per-bit names MSB first: bitNames("a",3) → a2 a1 a0 */
const bitNames=(b,n)=>Array.from({length:n},(_,i)=>b+(n-1-i));
/* {a:5} ← {a2:1,a1:0,a0:1} */
function ptGather(v, base, n){ let x=0; for(let i=0;i<n;i++) x|=(v[base+i]?1:0)<<i; return x; }

/* ---- the catalogue ----
   ports: {in:{base:width}, out:{base:width}} at part level (a bus of n bits is ONE base).
   ref(inputs)→outputs over those bases (combinational); seq: {cycles, drive(i)→inputs, init, step(state,in)→{state,out}}. */
const PARTS = {
  half_adder:{ label:"Half adder", group:"บวก/ลบ", desc:"sum = a⊕b, carry = a·b",
    ports:()=>({in:{a:1,b:1}, out:{sum:1,carry:1}}), ref:v=>({sum:v.a^v.b, carry:v.a&v.b}),
    build:()=>{ const t=ptIntent("half_adder"), a=t.IN("a"), b=t.IN("b"); t.OUT("sum", t.G("XOR",[a,b])); t.OUT("carry", t.G("AND",[a,b])); return t; } },
  full_adder:{ label:"Full adder", group:"บวก/ลบ", desc:"sum = a⊕b⊕cin, cout = a·b + cin·(a⊕b) — XOR/AND/OR แบบในตำรา",
    ports:()=>({in:{a:1,b:1,cin:1}, out:{sum:1,cout:1}}), ref:v=>{ const s=v.a+v.b+v.cin; return {sum:s&1, cout:s>>1}; },
    build:()=>{ const t=ptIntent("full_adder"), a=t.IN("a"), b=t.IN("b"), c=t.IN("cin");
      const x=t.G("XOR",[a,b]); t.OUT("sum", t.G("XOR",[x,c])); t.OUT("cout", t.G("OR",[t.G("AND",[a,b]), t.G("AND",[x,c])])); return t; } },
  half_subtractor:{ label:"Half subtractor", group:"บวก/ลบ", desc:"diff = a⊕b, borrow = a'·b",
    ports:()=>({in:{a:1,b:1}, out:{diff:1,borrow:1}}), ref:v=>({diff:v.a^v.b, borrow:(!v.a&&v.b)?1:0}),
    build:()=>{ const t=ptIntent("half_subtractor"), a=t.IN("a"), b=t.IN("b"); t.OUT("diff", t.G("XOR",[a,b])); t.OUT("borrow", t.G("AND",[t.G("NOT",[a]), b])); return t; } },
  full_subtractor:{ label:"Full subtractor", group:"บวก/ลบ", desc:"a − b − bin → diff, bout",
    ports:()=>({in:{a:1,b:1,bin:1}, out:{diff:1,bout:1}}), ref:v=>{ const d=v.a-v.b-v.bin; return {diff:d&1, bout:d<0?1:0}; },
    build:()=>{ const t=ptIntent("full_subtractor"), a=t.IN("a"), b=t.IN("b"), c=t.IN("bin");
      const x=t.G("XOR",[a,b]); t.OUT("diff", t.G("XOR",[x,c]));
      t.OUT("bout", t.G("OR",[t.G("AND",[t.G("NOT",[a]), b]), t.G("AND",[t.G("NOT",[x]), c])])); return t; } },
  adder:{ label:"ตัวบวก N บิต (ripple carry)", group:"บวก/ลบ", desc:"s = a + b + cin, cout = บิตทด · n = 1..8 · cin:false = ไม่มีขา cin",
    params:{n:{min:1,max:8,def:4}, cin:{bool:true,def:true}},
    ports:p=>({in:Object.assign({a:p.n,b:p.n}, p.cin?{cin:1}:{}), out:{s:p.n, cout:1}}),
    ref:(v,p)=>{ const s=v.a+v.b+(p.cin?v.cin:0); return {s:s&((1<<p.n)-1), cout:(s>>p.n)&1}; },
    build:p=>{ const t=ptIntent("adder"+p.n); const A=[],B=[];
      for(let i=0;i<p.n;i++){ A.push(t.IN("a"+i)); B.push(t.IN("b"+i)); }
      let c=p.cin?t.IN("cin"):null;
      for(let i=0;i<p.n;i++){ const x=t.G("XOR",[A[i],B[i]]);
        if(c==null){ t.OUT("s"+i, x); c=t.G("AND",[A[i],B[i]]); continue; }
        t.OUT("s"+i, t.G("XOR",[x,c])); c=t.G("OR",[t.G("AND",[A[i],B[i]]), t.G("AND",[x,c])]); }
      t.OUT("cout", c); return t; } },
  subtractor:{ label:"ตัวลบ N บิต", group:"บวก/ลบ", desc:"d = a − b (a + b' + 1), bout = 1 เมื่อ a < b · n = 1..8",
    params:{n:{min:1,max:8,def:4}},
    ports:p=>({in:{a:p.n,b:p.n}, out:{d:p.n, bout:1}}),
    ref:(v,p)=>{ const d=v.a-v.b; return {d:d&((1<<p.n)-1), bout:d<0?1:0}; },
    build:p=>{ const t=ptIntent("subtractor"+p.n); const A=[],B=[];
      for(let i=0;i<p.n;i++){ A.push(t.IN("a"+i)); B.push(t.IN("b"+i)); }
      let c=t.X("VCC");
      for(let i=0;i<p.n;i++){ const nb=t.G("NOT",[B[i]]), x=t.G("XOR",[A[i],nb]);
        t.OUT("d"+i, t.G("XOR",[x,c])); c=t.G("OR",[t.G("AND",[A[i],nb]), t.G("AND",[x,c])]); }
      t.OUT("bout", t.G("NOT",[c])); return t; } },
  comparator:{ label:"ตัวเปรียบเทียบ N บิต", group:"เปรียบเทียบ", desc:"eq (a=b), gt (a>b), lt (a<b) — จากบิตสูงลงต่ำแบบในตำรา · n = 1..8",
    params:{n:{min:1,max:8,def:4}},
    ports:p=>({in:{a:p.n,b:p.n}, out:{eq:1,gt:1,lt:1}}), ref:v=>({eq:v.a===v.b?1:0, gt:v.a>v.b?1:0, lt:v.a<v.b?1:0}),
    // e_i = a_i ⊙ b_i ; gt = Σ_i a_i·b_i'·(e_j for every higher j) ; lt likewise ; eq = Π e_i
    build:p=>{ const t=ptIntent("comparator"+p.n), A=[], B=[];
      for(let i=p.n-1;i>=0;i--){ A[i]=t.IN("a"+i); B[i]=t.IN("b"+i); }
      const E=[], G=[], L=[];
      for(let i=0;i<p.n;i++){ E[i]=t.G("XNOR",[A[i],B[i]]); G[i]=t.G("AND",[A[i], t.G("NOT",[B[i]])]); L[i]=t.G("AND",[t.G("NOT",[A[i]]), B[i]]); }
      const chain=X=>{ const terms=[]; for(let i=p.n-1;i>=0;i--){ const hi=E.slice(i+1); terms.push(hi.length?t.G("AND",[X[i], ...hi]):X[i]); }
        return terms.length>1?t.G("OR",terms):terms[0]; };
      t.OUT("eq", p.n>1?t.G("AND",E):E[0]); t.OUT("gt", chain(G)); t.OUT("lt", chain(L)); return t; } },
  mux:{ label:"MUX N:1", group:"เลือกข้อมูล", desc:"y = d[s] · n = 2, 4, 8 ขาข้อมูล (s0 = บิตต่ำ)",
    params:{n:{options:[2,4,8],def:4}},
    ports:p=>({in:{d:p.n, s:Math.log2(p.n)}, out:{y:1}}), ref:v=>({y:ptBits(v.d, v.s)}),
    build:p=>{ const t=ptIntent("mux"+p.n+"to1"), m=t.X("MUX",{params:{inputs:p.n}});
      for(let i=0;i<p.n;i++) t.W(t.IN("d"+i), m+".d"+i);
      for(let i=0;i<Math.log2(p.n);i++) t.W(t.IN("s"+i), m+".s"+i);
      t.OUT("y", m+".y"); return t; } },
  demux:{ label:"DEMUX 1:N", group:"เลือกข้อมูล", desc:"y[s] = d, ขาอื่น 0 · n = 2, 4, 8",
    params:{n:{options:[2,4,8],def:4}},
    ports:p=>({in:{d:1, s:Math.log2(p.n)}, out:{y:p.n}}), ref:v=>({y:v.d?(1<<v.s):0}),
    build:p=>{ const k=Math.log2(p.n); return ptFromTable("demux1to"+p.n, ["d", ...bitNames("s",k)], Array.from({length:p.n},(_,i)=>"y"+i),
      v=>{ const s=ptGather(v,"s",k), o={}; for(let i=0;i<p.n;i++) o["y"+i]=v.d&&s===i; return o; }); } },
  decoder:{ label:"Decoder n→2ⁿ", group:"ถอด/เข้ารหัส", desc:"y[a] = 1 ขาเดียว (active-high) · n = 1..4 · en:true เพิ่มขา enable",
    params:{n:{min:1,max:4,def:3}, en:{bool:true,def:false}},
    ports:p=>({in:Object.assign({a:p.n}, p.en?{en:1}:{}), out:{y:1<<p.n}}), ref:(v,p)=>({y:(!p.en||v.en)?(1<<v.a):0}),
    build:p=>ptFromTable("decoder"+p.n+"to"+(1<<p.n), [...(p.en?["en"]:[]), ...bitNames("a",p.n)], Array.from({length:1<<p.n},(_,i)=>"y"+i),
      v=>{ const a=ptGather(v,"a",p.n), o={}; for(let i=0;i<(1<<p.n);i++) o["y"+i]=(!p.en||v.en)&&a===i; return o; }) },
  encoder:{ label:"Priority encoder", group:"ถอด/เข้ารหัส", desc:"a = ตำแหน่ง d ที่สูงสุดที่เป็น 1, v = มีขาใดเป็น 1 · n = 4, 8",
    params:{n:{options:[4,8],def:4}},
    ports:p=>({in:{d:p.n}, out:{a:Math.log2(p.n), v:1}}),
    ref:(v,p)=>{ let a=0; for(let i=0;i<p.n;i++) if(ptBits(v.d,i)) a=i; return {a, v:v.d?1:0}; },
    build:p=>{ const k=Math.log2(p.n); return ptFromTable("prio_enc"+p.n, bitNames("d",p.n), [...bitNames("a",k), "v"],
      v=>{ const d=ptGather(v,"d",p.n); let a=0; for(let i=0;i<p.n;i++) if(ptBits(d,i)) a=i; const o={v:d?1:0}; for(let i=0;i<k;i++) o["a"+i]=ptBits(a,i); return o; }); } },
  bcd_7seg:{ label:"BCD → 7-segment", group:"ถอด/เข้ารหัส", desc:"b (4 บิต) → a..g · active_low:true สำหรับบอร์ด EDGE (common anode) · 10–15 ไม่สนใจ",
    params:{active_low:{bool:true,def:true}},
    ports:()=>({in:{b:4}, out:{a:1,b:1,c:1,d:1,e:1,f:1,g:1}}),       // input b[3:0] and segment b are different sides
    ref:(v,p)=>{ if(v.b>9) return null; const o={}; for(const s of "abcdefg"){ const on=SEG7[s][v.b]==="1"; o[s]=(p.active_low?!on:on)?1:0; } return o; },
    build:p=>{ const P=seg7Preset(!!p.active_low); const t=ttToIntent(P.inputs, P.outputs, P.rows, P.module); if(t.error) throw new Error(t.error); return t.intent; } },
  parity:{ label:"Parity generator", group:"อื่นๆ", desc:"p = XOR ทุกบิต (even: รวม p แล้วมี 1 เป็นคู่) · odd:true กลับ · n = 2..8",
    params:{n:{min:2,max:8,def:4}, odd:{bool:true,def:false}},
    ports:p=>({in:{d:p.n}, out:{p:1}}),
    ref:(v,p)=>{ let x=0; for(let i=0;i<p.n;i++) x^=ptBits(v.d,i); return {p:p.odd?x^1:x}; },
    build:p=>{ const t=ptIntent((p.odd?"odd":"even")+"_parity"+p.n); let x=t.IN("d0");
      for(let i=1;i<p.n;i++) x=t.G("XOR",[x, t.IN("d"+i)]);
      t.OUT("p", p.odd?t.G("NOT",[x]):x); return t; } },
  majority:{ label:"Majority (3 อินพุต)", group:"อื่นๆ", desc:"y = 1 เมื่อ 1 อย่างน้อย 2 ใน 3",
    ports:()=>({in:{a:1,b:1,c:1}, out:{y:1}}), ref:v=>({y:(v.a+v.b+v.c)>=2?1:0}),
    build:()=>{ const t=ptIntent("majority3"), a=t.IN("a"), b=t.IN("b"), c=t.IN("c");
      t.OUT("y", t.G("OR",[t.G("AND",[a,b]), t.G("AND",[a,c]), t.G("AND",[b,c])])); return t; } },
  // ---------------- sequential ----------------
  mod_counter:{ label:"ตัวนับ mod-N (D-FF, synchronous)", group:"ตัวนับ", desc:"q นับ 0 … N−1 แล้ววน · N = 2..64 · ขา clk",
    params:{n:{min:2,max:64,def:10}},
    ports:p=>({in:{clk:1}, out:{q:Math.max(1,(p.n-1).toString(2).length)}}),
    build:p=>{ const it=fsmCounterIntent(Array.from({length:p.n},(_,i)=>i)); if(!it||it.error) throw new Error((it&&it.error)||"too large"); it.module="mod"+p.n; return it; },
    seq:p=>({cycles:Math.min(3*p.n,140), init:0, drive:()=>({}), step:(s)=>({out:{q:s}, state:(s+1)%p.n})}) },
  bcd_counter:{ label:"ตัวนับ BCD (0–9)", group:"ตัวนับ", desc:"mod-10 · q[3:0]",
    ports:()=>({in:{clk:1}, out:{q:4}}),
    build:()=>{ const it=fsmCounterIntent([0,1,2,3,4,5,6,7,8,9]); it.module="bcd_counter"; return it; },
    seq:()=>({cycles:25, init:0, drive:()=>({}), step:s=>({out:{q:s}, state:(s+1)%10})}) },
  jk_counter:{ label:"ตัวนับ/หารความถี่ JK-FF", group:"ตัวนับ", desc:"synchronous JK-FF mod-N แบบในแลป · output:'q' = ออกทุกบิต, ไม่ใส่ = clk_out (บิตสูงสุด) · N = 2..64",
    params:{n:{min:2,max:64,def:10}, output:{options:["clk_out","q"],def:"clk_out"}},
    ports:p=>{ const b=Math.max(1,(p.n-1).toString(2).length); return {in:{clk_in:1}, out:p.output==="q"?{q:b}:{clk_out:1}}; },
    build:p=>{ const r=jkCounterIntent(Array.from({length:p.n},(_,i)=>i), p.output==="q"?{outputs:"q"}:{}); if(r.error) throw new Error(r.error); r.module="jkmod"+p.n; return r; },
    after:(sch,p,it)=>{ if(typeof jkLayout==="function") jkLayout(sch, it.bits); },
    seq:p=>{ const b=Math.max(1,(p.n-1).toString(2).length);
      return {cycles:Math.min(3*p.n,140), init:0, drive:()=>({}), step:s=>({out:p.output==="q"?{q:s}:{clk_out:(s>>(b-1))&1}, state:(s+1)%p.n})}; } },
  binary_counter:{ label:"ตัวนับไบนารี (ripple)", group:"ตัวนับ", desc:"นับขึ้น 0 … 2ⁿ−1 · T-FF ต่อแบบ ripple · n = 1..8 บิต",
    params:{n:{min:1,max:8,def:4}},
    ports:p=>({in:{clk:1}, out:{q:p.n}}),
    build:p=>{ const b=seqBuildIntent("counter "+p.n+" bit"); return b.intent; },
    seq:p=>({cycles:Math.min(3*(1<<p.n),140), init:0, drive:()=>({}), step:s=>({out:{q:s}, state:(s+1)%(1<<p.n)})}) },
  clock_divider:{ label:"หารความถี่ ÷N", group:"ตัวนับ", desc:"clk_out = clk_in / N (N คู่ = duty 50%) · N = 2 … 2³¹ เช่น 50 MHz → 1 Hz = 50000000",
    params:{n:{min:2,max:2147483648,def:50}},
    ports:()=>({in:{clk_in:1}, out:{clk_out:1}}),
    build:p=>{ const r=dividerIntent(p.n); if(r.error) throw new Error(r.error); return r; },
    // a big N cannot be run clock by clock: check the same generator on a small N of the same parity
    seq:p=>{ const N=p.n>64?(p.n%2?63:62):p.n, M=N%2?N:N/2, bits=Math.max(1,(M-1).toString(2).length);
      return {small:N!==p.n?N:null, cycles:Math.min(3*N,200), init:{c:0,t:0}, drive:()=>({}),
        step:s=>{ const out={clk_out: N%2 ? (s.c>>(bits-1))&1 : s.t};
          const wrap=s.c===M-1; return {out, state:{c:wrap?0:s.c+1, t:N%2?0:(wrap?s.t^1:s.t)}}; }}; } },
  shift_register:{ label:"Shift register", group:"เก็บข้อมูล", desc:"sin เลื่อนเข้าทีละ clock: q0 ← sin, q1 ← q0 … · n = 1..16",
    params:{n:{min:1,max:16,def:4}},
    ports:p=>({in:{clk:1, sin:1}, out:{q:p.n}}),
    build:p=>seqBuildIntent("shift register "+p.n+" bit").intent,
    seq:p=>({cycles:20, init:0, drive:i=>({sin:[1,0,1,1,0,0,1,0,1,1,1,0,0,1,0,1,0,0,1,1][i]}),
      step:(s,v)=>({out:{q:s}, state:((s<<1)|v.sin)&((1<<p.n)-1)})}) },
  register:{ label:"Register N บิต", group:"เก็บข้อมูล", desc:"q ← d ทุกขอบขาขึ้นของ clk · n = 2..16",
    params:{n:{min:2,max:16,def:4}},
    ports:p=>({in:{clk:1, d:p.n}, out:{q:p.n}}),
    build:p=>seqBuildIntent("register "+p.n+" bit").intent,
    seq:p=>({cycles:16, init:0, drive:i=>({d:(i*37+11)&((1<<p.n)-1)}), step:(s,v)=>({out:{q:s}, state:v.d})}) },
  toggle:{ label:"Toggle (T flip-flop)", group:"เก็บข้อมูล", desc:"q กลับค่าทุกครั้งที่ btn มีขอบขาขึ้น (กดปุ่ม = เปิด/ปิด)",
    ports:()=>({in:{btn:1}, out:{q:1}}),
    build:()=>{ const t=ptIntent("toggle"), b=t.IN("btn"), f=t.X("DFF"); t.W(b, f+".clk"); t.W(f+".qn", f+".d"); t.OUT("q", f+".q"); return t; },
    seq:()=>({cycles:8, init:0, drive:()=>({}), step:s=>({out:{q:s}, state:s^1})}) },
  edge_detector:{ label:"ตัวจับขอบขาขึ้น", group:"เก็บข้อมูล", desc:"pulse = 1 หนึ่ง clock เมื่อ x เปลี่ยนจาก 0 เป็น 1",
    ports:()=>({in:{clk:1, x:1}, out:{pulse:1}}),
    build:()=>{ const t=ptIntent("edge_detect"), c=t.IN("clk"), x=t.IN("x"), f=t.X("DFF");
      t.W(c, f+".clk"); t.W(x, f+".d"); t.OUT("pulse", t.G("AND",[x, f+".qn"])); return t; },
    seq:()=>({cycles:14, init:0, drive:i=>({x:[0,1,1,1,0,0,1,0,1,1,0,1,1,0][i]}), step:(s,v)=>({out:{pulse:v.x&&!s?1:0}, state:v.x})}) },
  debounce:{ label:"Debounce (3 ตัวอย่าง)", group:"เก็บข้อมูล", desc:"y = 1 เมื่อ x เป็น 1 ครบ 3 clock ติดกัน — ใช้ clock ช้า (เช่น ~100 Hz จากตัวหารความถี่)",
    ports:()=>({in:{clk:1, x:1}, out:{y:1}}),
    build:()=>{ const t=ptIntent("debounce3"), c=t.IN("clk"), x=t.IN("x"); const F=[0,1,2].map(()=>t.X("DFF"));
      F.forEach((f,i)=>{ t.W(c, f+".clk"); t.W(i?F[i-1]+".q":x, f+".d"); });
      t.OUT("y", t.G("AND", F.map(f=>f+".q"))); return t; },
    seq:()=>({cycles:16, init:0, drive:i=>({x:[1,0,1,1,1,1,0,1,1,1,1,1,0,0,0,1][i]}),
      step:(s,v)=>({out:{y:(s&7)===7?1:0}, state:((s<<1)|v.x)&7})}) },
};

/* ---- params: defaults, ranges ---- */
/* a part's own settings may also come nested — {kind, params:{format:"mm.ss", down:true}} (lab 7: they
   were dropped and the default 00-99 counter was drawn without a word) */
function partArgs(a){ return a && a.params && typeof a.params==="object" ? Object.assign({}, a, a.params) : (a||{}); }
const PART_GENERIC=new Set(["kind","part","type","module","sheet","name","bus","replace","params","x","y","top","pins","label","id","_check","generator"]);
/* settings this part does not have are refused, naming the ones it has (MCP entry points) */
function partCheckArgs(kind, a){
  const P=PARTS[kind]; if(!P) return;
  const own=Object.keys(P.params||{}), bad=Object.keys(partArgs(a)).filter(k=>!own.includes(k) && !PART_GENERIC.has(k));
  if(bad.length) mcpFail(`${kind} has no setting ${bad.map(k=>"'"+k+"'").join(", ")}`,
    own.length ? `${kind} takes: ${own.map(k=>k+"="+JSON.stringify(P.params[k].def)+(P.params[k].options?" ("+P.params[k].options.join("|")+")":"")).join(", ")}` : `${kind} has no settings`);
}
function partParams(kind, a){
  const P=PARTS[kind]; const out={}; a=partArgs(a);
  Object.entries(P.params||{}).forEach(([k,s])=>{
    let v=a[k]!=null?a[k]:s.def;
    if(s.bool) v=v===true||v==="true"||v===1;
    else if(s.options){ v=typeof s.def==="number"?+v:String(v); if(!s.options.includes(v)) mcpFail(`${kind}.${k} must be one of ${s.options.join(", ")}`); }
    else { v=Math.floor(+v); if(!(v>=s.min && v<=s.max)) mcpFail(`${kind}.${k} must be ${s.min}..${s.max}`); }
    out[k]=v; });
  return out;
}

/* ---- the check: the drawn sheet against the part's reference ---- */
function partPortMap(sch){      // base → [{name, bit|null, width}] for every IN/OUT on the sheet
  const m={in:{}, out:{}};
  sch.components.filter(c=>c.type==="IN"||c.type==="OUT").forEach(c=>{
    const nm=String(c.params.name), w=Math.max(1,+(c.params.width||1)), side=c.type==="IN"?"in":"out";
    const mm=/^(.*?[A-Za-z_])(\d+)$/.exec(nm);
    const add=(base,bit)=>{ (m[side][base]=m[side][base]||[]).push({name:nm, bit, width:w}); };
    if(w>1) add(nm,null); else if(mm) { add(mm[1], +mm[2]); add(nm, null); } else add(nm, null);
  });
  return m;
}
function partVerifyComb(sch, part, p){
  const ports=part.ports(p), pm=partPortMap(sch);
  const ins=Object.entries(ports.in), outs=Object.entries(ports.out).filter(([,w])=>w>0);
  const total=ins.reduce((n,[,w])=>n+w,0);
  // sheet inputs for part-level values: a bus port takes the value, per-bit ports their bit
  const drive=v=>{ const o={}; ins.forEach(([b,w])=>{ const L=pm.in[b]||[];
      const bus=L.find(x=>x.bit==null && x.width>1) || (w===1 && L.find(x=>x.bit==null));
      if(bus) o[bus.name]=v[b]; else L.filter(x=>x.bit!=null).forEach(x=>o[x.name]=ptBits(v[b], x.bit)); }); return o; };
  const read=(got,b,w)=>{ const L=pm.out[b]||[]; const bus=L.find(x=>x.bit==null && (x.width>1 || w===1));
      const num=x=>typeof x==="string" ? parseInt(x,2) : (x==="undriven"?NaN:+x);
      if(bus) return num(got[bus.name]);
      let s=0; for(const x of L.filter(y=>y.bit!=null)){ const bv=num(got[x.name]); if(isNaN(bv)) return NaN; s|=bv<<x.bit; } return s; };
  const fs=flattenSchematic(sch).sch, st=probeStruct(fs);
  const vectors=[];
  if(total<=10){ for(let r=0;r<(1<<total);r++){ let k=0; const v={}; ins.forEach(([b,w])=>{ v[b]=(r>>k)&((1<<w)-1); k+=w; }); vectors.push(v); } }
  else { let seed=12345; const rnd=()=>{ seed=(Math.imul(seed,1103515245)+12345)>>>0; return seed; };
    const corner=[0,1]; for(const cz of corner) vectors.push(Object.fromEntries(ins.map(([b,w])=>[b, cz?((1<<w)-1):0])));
    for(let i=0;i<300;i++) vectors.push(Object.fromEntries(ins.map(([b,w])=>[b, rnd()&((1<<w)-1)]))); }
  let bad=null;
  for(const v of vectors){
    const want=part.ref(v,p); if(!want) continue;                     // a don't-care row (BCD 10–15)
    const got=mcpEvalOuts(sch, fs, st, drive(v));
    for(const [b,w] of outs){ if(want[b]==null) continue; const g=read(got,b,w);
      if(g!==want[b]){ bad={inputs:v, output:b, want:want[b], got:g}; break; } }
    if(bad) break;
  }
  return {pass:!bad, method: total<=10 ? `ทุกแถว (${vectors.length} แถว)` : `${vectors.length} ชุดอินพุต (มุม + สุ่ม)`, mismatch:bad||undefined};
}
function partVerifySeq(sch, part, p){
  const S=part.seq(p), ports=part.ports(p), pm=partPortMap(sch);
  if(S.small) return {pass:false, method:"—", mismatch:{reason:"too many clocks to run one by one — check a copy built at "+JSON.stringify(S.small)}};
  const ins=sch.components.filter(c=>c.type==="IN");
  const byName=n=>ins.find(c=>c.params.name===n);
  const holdAt=i=>{ const v=S.drive(i)||{}, o={};
    Object.entries(v).forEach(([b,val])=>{ const L=pm.in[b]||[]; const bus=L.find(x=>x.bit==null && (x.width>1 || (ports.in[b]||1)===1));
      if(bus){ const c=byName(bus.name); if(c) o[c.id]=val; }
      else L.filter(x=>x.bit!=null).forEach(x=>{ const c=byName(x.name); if(c) o[c.id]=ptBits(val,x.bit); }); });
    return o; };
  const j=clientSeqSim(sch, S.cycles, {holdAt, hold:holdAt(0)});
  if(!j.ok) return {pass:false, method:"จำลองไม่ได้", mismatch:{reason:j.reason}};
  const sq=j.sequence, outNames=sq.outputs;
  const val=(row,b)=>{ const L=pm.out[b]||[]; const bus=L.find(x=>x.bit==null && (x.width>1 || (ports.out[b]||1)===1));
    const at=n=>{ const k=outNames.indexOf(n); return k<0?NaN:(row[4]?row[4][k]:row[3][k]); };
    if(bus) return at(bus.name);
    let s=0; for(const x of L.filter(y=>y.bit!=null)) s|=(at(x.name)?1:0)<<x.bit; return s; };
  let s=S.init, bad=null;
  for(let i=0;i<sq.rows.length && !bad;i++){
    const r=S.step(s, S.drive(i)||{});
    for(const [b,want] of Object.entries(r.out)){ const g=val(sq.rows[i], b); if(g!==want){ bad={cycle:i, output:b, want, got:g}; break; } }
    s=r.state;
  }
  return {pass:!bad, method:`${sq.rows.length} clock เทียบกับโมเดลสถานะ`, mismatch:bad||undefined};
}
/* draw a part on a new sheet, check it; returns {sch, verify, intent} — throws (and removes the sheet) if the check fails */
function partBuild(kind, a){
  const part=PARTS[kind]; if(!part) mcpFail(`unknown part '${kind}'`, "list_parts shows them: "+Object.keys(PARTS).join(", "));
  const p=partParams(kind, a||{});
  let it=part.build(p); if(it && it.W) it={module:it.module, components:it.components, nets:it.nets};
  const bits=it.bits;
  it.module=sanId(a.name||it.module||kind);
  // the throw-away copy a big part is checked on needs connections, not routed wires (20 s for lab 6's top)
  const dr=a._check ? drawIntent(it, {noRoute:true}) : aiDrawIntent(it);
  if(!dr||!dr.ok) mcpFail("could not draw the part: "+((dr&&(dr.error||(dr.errors||[]).map(e=>e.msg||e).join("; ")))||"?"));
  const sch=dr.sch;
  if(part.after) part.after(sch, p, Object.assign({bits}, it));
  // the block's pins in the part's own order (a3..a0, b3..b0, cin | s3..s0, cout; 7-seg a..g), not the layout's
  const ports=part.ports(p);
  const order=side=>{ const bases=Object.keys(ports[side]);
    const key=n=>{ const m=/^(.*?[A-Za-z_])(\d+)$/.exec(n), base=m&&bases.includes(m[1])?m[1]:n, bi=bases.indexOf(base);
      return [bi<0?99:bi, base!==n?-(+m[2]):0]; };
    return sch.components.filter(c=>c.type===(side==="in"?"IN":"OUT")).map(c=>String(c.params.name))
      .sort((x,y)=>{ const A=key(x), B=key(y); return (A[0]-B[0])||(A[1]-B[1]); }); };
  sch.portOrder={in:order("in"), out:order("out")};
  if(a.bus){ const was=sch.locked; sch.locked=false; busifyPorts(sch, a.bus); sch.locked=was; }
  // a big divider cannot be run clock by clock: its generator is checked on a small N instead
  let v;
  if(part.seq){ const S=part.seq(p);
    if(S.small){ const sp=typeof S.small==="object"?S.small:{n:S.small}, had=new Set(Object.keys(state.project.schematics));
      const tmp=partBuild(kind, Object.assign({}, a, sp, {name:"__chk", bus:false, _check:true}));
      // the check copy and any sub-sheet only it needed (a small divider) go again
      Object.keys(state.project.schematics).forEach(id=>{ if(!had.has(id)) delete state.project.schematics[id]; });
      state.openTabs=(state.openTabs||[]).filter(i=>state.project.schematics[i]);
      v=Object.assign({}, tmp.verify, {method:`ตัวสร้างเดียวกันที่ ${Object.entries(sp).map(([k,x])=>(k==="n"?"N":k)+"="+x).join(", ")}: `+tmp.verify.method}); }
    else v=partVerifySeq(sch, part, p); }
  else v=partVerifyComb(sch, part, p);
  if(!v.pass){ delete state.project.schematics[sch.id]; state.openTabs=(state.openTabs||[]).filter(i=>i!==sch.id); renderAll();
    mcpFail(`internal check failed for ${kind}: `+JSON.stringify(v.mismatch), "this is a bug in the part library — please report it"); }
  sheetVerifyStamp(sch, `part ${kind} ${JSON.stringify(p)} — ${v.method}`);
  return {sch, verify:v, params:p};
}

/* ---------- MCP ---------- */
MCP_OPS.list_parts = a=>{
  const q=String(a.query||"").toLowerCase();
  return {parts:Object.entries(PARTS).filter(([k,P])=>!q || (k+" "+P.label+" "+P.desc+" "+P.group).toLowerCase().includes(q)).map(([k,P])=>{
    const p={}; Object.entries(P.params||{}).forEach(([n,s])=>p[n]=s.options?s.options:s.bool?"true/false":`${s.min}..${s.max}`);
    let ports=null; try{ const d={}; Object.entries(P.params||{}).forEach(([n,s])=>d[n]=s.def); const pp=P.ports(d);
      ports={in:Object.entries(pp.in).map(([b,w])=>w>1?`${b}[${w-1}:0]`:b), out:Object.entries(pp.out).filter(([,w])=>w>0).map(([b,w])=>w>1?`${b}[${w-1}:0]`:b)}; }catch(_){}
    return {kind:k, label:P.label, group:P.group, description:P.desc, params:p, sequential:!!P.seq, ports_with_defaults:ports}; }),
    note:"per-bit ports are named a0, a1 … unless bus:true (then a[n-1:0]); every part is checked against a reference model when it is built"};
};
MCP_OPS.build_part = a=>{
  const kind=String(a.kind||"").trim(); if(!kind) mcpFail("kind is required", "list_parts shows the kinds");
  const P=state.project.schematics, want=a.sheet?String(a.sheet).trim():"";
  const tgt=want?Object.values(P).find(s=>String(s.name).toLowerCase()===want.toLowerCase()):null;
  if(tgt && tgt.components.some(c=>c.type!=="JUNCTION")) mcpFail(`sheet '${tgt.name}' already has parts`, "give a new sheet name (it is created), or an empty sheet — or delete_sheet it first to rebuild it");
  if(PARTS[kind]) partCheckArgs(kind, a);
  mcpBeforeChange("สร้าง "+kind);
  const r=partBuild(kind, partArgs(a));
  let sch=r.sch;
  if(tgt){ tgt.components=sch.components; tgt.wires=sch.wires; ["portOrder","locked","verified","pinmap"].forEach(k=>{ if(sch[k]!=null) tgt[k]=sch[k]; });
    delete P[sch.id]; state.openTabs=(state.openTabs||[]).filter(i=>i!==sch.id); sch=tgt; sheetVerifyStamp(sch, sch.verified.how); }
  else if(want) sch.name=uniqueSchName(want, sch.id);
  openSchTab(sch.id); mcpActivity("สร้าง "+PARTS[kind].label); mcpCommit(sch); try{ zoomFit(); }catch(_){}
  return {sheet:sch.name, kind, params:r.params, ports:schPortList(sch).map(p=>({name:p.id, dir:p.dir, width:p.width})),
    verified:{pass:true, method:r.verify.method}, parts:sch.components.filter(c=>c.type!=="JUNCTION").length,
    note:"verified against the part's reference model — no need to rebuild it; place it on another sheet as block:"+sch.name};
};
